Zettel: A bunch of new zettel utilities and changes

diff --git a/zfix b/zfix
--- a/zfix
+++ b/zfix
@@ -1,21 +1,89 @@
 #!/usr/bin/bash
 
 hgtimestamp=$HOME/Dropbox/Doc/zettel/.hgtimestamp
-file="$1"
 
+function usage() {
+    echo "Usage: zfix [--fromname|-f] [--oldname|-o slug] <zettel-file>"
+}
+
+function pprint_date() {
+    echo -n $(date -d"$1" '+%Y-%m-%d %H:%M')
+}
+
+if [[ $# -lt 1 ]]; then
+    usage
+    exit 1
+fi
+
+# Process command line options
+file=
+basename=
+fromname=
+oldname=
+while [ "$1" != "" ]; do
+    case "$1" in
+        -f | --fromname )
+            fromname=1
+            ;;
+        -o | --oldname )
+            shift
+            oldname=$1
+            ;;
+        * )
+            file="$1"
+            basename=$(basename "$file")
+    esac
+    shift
+done
+
+# Get the modified and created dates from the file
 if [[ $(grep -E '^modified:' $file) =~ ^modified:[[:space:]]+([0-9-]{10}) ||
     $(grep -E '^created:' $file) =~ ^created:[[:space:]]+([0-9-]{10}) ]]; then
     moddate=$(date -d @$(stat -c'%Y' "$file") "+%Y-%m-%d")
-    #echo "File 'modified' line: ${BASH_REMATCH[1]}, file modification date: $moddate"
+    #echo "zfix: File 'modified' line: ${BASH_REMATCH[1]}, file modification date: $moddate"
+    
     if [[ "${BASH_REMATCH[1]}" == "$moddate" ]]; then
-        echo "File's modification date and modified line match, skipping"
+        echo "zfix: $basename: File's modification date and modified line match, skipping"
         exit 0
     fi
 fi
 
-# sample: "tech/363-d.txt": {"timestamp": 1436311993.0},
-time=$(grep $(grep "oldname" "$file" | awk -e '{ print $2 ".txt" }') $hgtimestamp)
-if [[ "$time" =~ ([0-9]{10})\.[0-9] ]]; then
-    echo "Success! Retouching $file to $(date -d@${BASH_REMATCH[1]} '+%Y-%m-%d %H:%M')"
-    touch -d "@${BASH_REMATCH[1]}" "$file"
+touchtime=
+if [[ $fromname -eq 1 ]]; then
+    if [[ "$file" =~ ([0-9]{8})T[0-9]{4} ]]; then
+        echo "zfix: $basename: Using filename date: ${BASH_REMATCH[1]}"
+        touchtime="${BASH_REMATCH[1]}"
+    else
+        echo "zfix: $basename: Can't parse filename to get time"
+    fi
+else
+    # Get the timestamp, either for $file or for its $oldname
+    #
+    # sample line from .hgtimestamp:
+    #       "tech/363-d.txt": {"timestamp": 1436311993.0},
+    timestamp=$(grep "[\"/]$basename" $hgtimestamp)
+    if [[ ! "$timestamp" && ! "$oldname" ]]; then
+        # No timestamp, and oldname is not given, so try to figure it out ourselves
+        if [[ "$file" ]] && grep -q "oldname" "$file"; then
+            # Oldname found in file, see if can get timestamp from it
+            oldname=$(grep "oldname" "$file" | tail -n1 | awk -e '{ print $2 ".txt" }')
+
+            timestamp=$(grep "[\"/]$oldname" $hgtimestamp)
+        else
+            echo "zfix: $basename: No timestamp for the file, and no oldname"
+            exit 1
+        fi
+    fi
+
+    # See if timestamp is valid
+    if [[ "$timestamp" =~ ([0-9]{10})\.[0-9]+},*$ ]]; then
+        touchtime="@${BASH_REMATCH[1]}"
+    else
+        echo "zfix: $basename: Timestamp ($timestamp) is invalid; oldname = $oldname"
+        exit 1
+    fi
 fi
+
+echo -n "zfix: $basename: Retouching to $(pprint_date $touchtime)..."
+touch -d "$touchtime" "$file"
+echo "Done"
diff --git a/zmakedate b/zmakedate
--- a/zmakedate
+++ b/zmakedate
@@ -5,14 +5,26 @@ zetteldir=$HOME/Dropbox/Doc/zettel
 limbodir=$zetteldir/limbo
 techdir=$zetteldir/tech
 personaldir=$zetteldir/personal
+writingdir=$zetteldir/writing
 
 function usage() {
-    echo "Usage: zmakedate [-t|--time <HHMM>] [-m|--move limbo|tech|personal] [-r|--retouch] <zettel-file>"
+    echo "Usage: zmakedate [-t <HHMM>] [-m ...] [-n] [-r] <slug>"
+    echo "  -t|--time <HHMM> -- use the given time"
+    echo "  -m|--move limbo|tech|personal|writing -- move to the designated sub-kasten"
+    echo "  -n|--rename -- "
+    echo "  -r|--retouch -- retouch"
+    echo "  -h|--help -- show this message"
 }
+
+if [[ $# -eq 0 ]]; then
+    usage
+    exit 1
+fi
 
 moveto="."
 fname=
 time=
+rename=
 retouch=
 origmodtime=
 while [ "$1" != "" ]; do
@@ -25,6 +37,8 @@ while [ "$1" != "" ]; do
                 moveto=$techdir
             elif [[ "$1" == "personal" ]]; then
                 moveto=$personaldir
+            elif [[ "$1" == "writing" ]]; then
+                moveto=$writingdir                
             else
                 echo "Error: Unknown move destination ($1); giving up"
                 exit 1
@@ -36,14 +50,27 @@ while [ "$1" != "" ]; do
             ;;
         -r | --retouch )
             retouch=1
-            origmodtime=$(stat -c'%Y' "$fname")
+            ;;
+        -n | --rename )
+            rename=1
             ;;
         -h | --help )
             usage
             exit
             ;;
         * )
-            fname="$1"
+            if [[ -e "$1" ]]; then
+                fname="$1"
+                origmodtime=$(stat -c'%Y' "$fname")
+            else
+                fname="$(zdirectory ${1})/${1}.txt"
+                fname="${fname##$zetteldir/}"
+                if [[ ! -e "$fname" ]]; then
+                    echo "Error: File '$1' does not exist"
+                    usage
+                    exit 1
+                fi
+            fi
     esac
     shift
 done
@@ -59,20 +86,27 @@ if [[ "$time" ]]; then
     fi
 else
     #
-    # Otherwise, try 0000, and if that fails, the modification time.
+    # Otherwise, try random time, and if that fails, the time of last
+    # modification or the time of last status change.
     #
-    datename=$(zdatename "$fname")
+    datename=$(zdatename -r "$fname")
     if [[ -e "$moveto/$datename" ]]; then
         regdatename=$datename
         datename=$(zdatename -m "$fname")
         if [[ -e "$moveto/$datename" ]]; then
-            echo "Error: Both regular ($regdatename) and modified ($datename) files exist"
-            exit 1
+            moddatename=$datename
+            datename=$(zdatename -c "$fname")
+            if [[ -e "$moveto/$datename" ]]; then
+                echo "Error: Can't move $fname because all attempted datenames already exist."
+                exit 1
+            fi
         fi
     fi
 fi
-hg mv --verbose "$fname" "$moveto/$datename"
 
-if [[ "$retouch" ]]; then
+# Move the file and fix references to it
+zmove "$fname" "$moveto/$datename"
+
+if [[ $? -eq 0 && "$retouch" ]]; then
     touch -d"@$origmodtime" "$moveto/$datename"
-else
+fi
