Changed: All commands now rely on /home/richard/Dropbox/Zettel

diff --git a/zgenfreq b/zgenfreq
--- a/zgenfreq
+++ b/zgenfreq
@@ -1,17 +1,25 @@
 #!/usr/bin/bash
-# Usage: zetgenfreq <frequency-file>
+# Generates the frequency file
 
-zetteldir=$HOME/Dropbox/Doc/zettel
-allzettel="$zetteldir/auto/all-zettel.dat"
-freqfile="$zetteldir/auto/word-frequency.dat"
+if [[ ! -v ZETTEL_DIR ]]; then
+    echo "$(basename $0): $ZETTEL_DIR is not set"
+    exit 1
+fi
+
+allzettel="$ZETTEL_DIR/auto/all-zettel.dat"
+freqfile="$ZETTEL_DIR/auto/word-frequency.dat"
 excludefile=/tmp/all-zettel.$$.exclude
 
+# Exclude the metadata keywords and common section names
 cat > $excludefile <<EOF
 created
 title
 modified
 oldname
-first-reading
+readings
+summary
+notes
+connections
 EOF
 
 # Create frequency file if it doesn't exist
@@ -28,6 +36,7 @@ fi
 # Doesn't do Unicode very well
 # tr -c '[:alnum:]' '[\n*]' < $1 | awk 'NF'
 
+# Replace all special symbols with space to prevent them confusing zwf
 sed -r -e 's/[.,:;?!(){}:@«»*"#\/_”`|]/ /g' -e 's/\[/ /g' -e 's/\]/ /g' < $allzettel |
     sed -e 's/\s/\n/g' |
     tr '[:upper:]' '[:lower:]' |
@@ -35,6 +44,6 @@ sed -r -e 's/[.,:;?!(){}:@«»*"#\/_”`|]/ /g' -e 's/\[/ /g' -e 's/\]/ /g' < $a
     fgrep -v -w -f $excludefile |
     sort | uniq -c | sort -nr | sed -re 's/\s+//' > $freqfile
 
-## Cleanup
+# Cleanup
 rm -f $excludefile
 
