bin/zgenfreq uses preset all-zettel.txt; moved its creation to bin/zcatall

diff --git a/zgenfreq b/zgenfreq
--- a/zgenfreq
+++ b/zgenfreq
@@ -1,14 +1,9 @@
-#!/bin/bash
+#!/usr/bin/bash
 # Usage: zetgenfreq <frequency-file>
 
-if [ $# -ne 1 ]; then
-    echo "Usage: zetgenfreq <frequency-file>"
-    exit 127
-fi
-
 zetteldir=$HOME/Dropbox/Doc/zettel
-allzettel=$zetteldir/auto/all-zettel.txt
-freqfile="$1"
+allzettel="$zetteldir/auto/all-zettel.txt"
+freqfile="$zetteldir/auto/zettel-word-frequency.txt"
 excludefile=/tmp/all-zettel.$$.exclude
 
 cat > $excludefile <<EOF
@@ -23,12 +18,10 @@ if [[ ! -e $freqfile ]]; then
     touch $freqfile
 fi
 
-# If frequency file is newer than allzettel file (or it doesn't exist), recreate
-# the latter
-if [[ $freqfile -nt $allzettel ]]; then
-    shopt -s globstar
-    cd $zetteldir
-    cat **/*.txt > $allzettel
+# Check that $allzettel file exists
+if [[ ! -e $allzettel ]]; then
+    echo "Error: No all-zettel file ($allzettel); run zcatall and rerun"
+    exit 1
 fi
 
 # Doesn't do Unicode very well
@@ -37,9 +30,8 @@ fi
 sed -r -e 's/[.,:;?!(){}:@«»*"#\/_”`|]/ /g' -e 's/\[/ /g' -e 's/\]/ /g' < $allzettel |
     sed -e 's/\s/\n/g' |
     tr '[:upper:]' '[:lower:]' |
-    grep -E '.{5}' |            # matches only words of 5+ characters
+    grep -E '.{3}' |            # matches only words of 3+ characters
     fgrep -v -w -f $excludefile |
-    fgrep -v -w -f /usr/share/groff/current/eign |
     sort | uniq -c | sort -nr | sed -re 's/\s+//' > $freqfile
 
 ## Cleanup
