Ztools: zretouch works on macOS

diff --git a/ztools/zretouch b/ztools/zretouch
--- a/ztools/zretouch
+++ b/ztools/zretouch
@@ -7,24 +7,32 @@ if [ $# -eq 1 ]; then
     file=$1
     filetop=$(head -4 $file)
 
-    # Prefer modification date in the file, followed by timestamped filename,
-    # followed by creation date in the file.
+    # Prefer modification date in the file followed by creation date in the
+    # file.
+    curtime=$(date +%H%M)
     if [[ "$filetop" =~ modified:[[:space:]]+([0-9-]{10}) ]]; then
-        time="${BASH_REMATCH[1]}"
-        echo "$file: $time";
+        date="${BASH_REMATCH[1]//-/}"
+        time=$curtime
+        echo "$file: modified on ${date}${time}";
     elif [[ "$file" =~ ([0-9]{8})T([0-9]{4}) ]]; then
-        time="${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
-        echo "$file: $time"
+        date="${BASH_REMATCH[1]}"
+        time="${BASH_REMATCH[2]}"
+        echo "$file: ISO8601 filename: ${date}T${time}"
     elif [[ "$filetop" =~ created:[[:space:]]+([0-9-]{10}) ]]; then
-        time="${BASH_REMATCH[1]}"
-        echo "$file: $time";
+        date="${BASH_REMATCH[1]//-/}"
+        time=$curtime
+        echo "$file: created on ${date}${time}";
     else
-        echo "$file: Cannot determine modification date";
+        echo "$file: Cannot determine modification or creation time";
+        date=""
         time=""
     fi
 
-    if [[ "$time" != "" ]]; then
-        touch -d "$time" $file;
+    if [[ "$date" != "" ]]; then
+        touch -t "${date}${time}" $file;
+        if [ $? -ne 0 ]; then
+            echo "Errored with this command: touch -t '${date}${time}' $file;"
+        fi
     fi
 else
     echo "Usage: $(basename $0) <filename>"
